version: '3'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=revisionQuestions
    volumes:
      - dbdata:/data/db
      # optional - ./db/seed.js:/docker-entrypoint-initdb.d/seed.js:ro
volumes:
  dbdata:
    name: questions

# DB_URL=mongodb://username:password@localhost:27017/database?authSource=admin